from .view_banner import *
from .view_donation import *
from .view_calendar import *
from .view_history import *
from .view_society_about import *
from .view_people import *
from .view_information import *
from .view_page_about import *
from .view_page_clinic_about import *
from .view_page_donation import *
